export const OrderStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  NOT_FULFILLING: 'NOT_FULFILLING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  ARRIVED: 'ARRIVED',
  PICKED_UP: 'PICKED_UP',
};
