export const OrderStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  NOT_FULFILLING: 'NOT_FULFILLING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
};
