ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_PICKUP';

ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PICKED_UP';

ALTER TABLE "products"
  ADD COLUMN IF NOT EXISTS "vipOnly" BOOLEAN NOT NULL DEFAULT false;
