-- Tenant-scope previously-global unique constraints so each tenant can hold its own
-- category names, variant SKUs, and settings keys without cross-tenant collision.
-- (These three were missed when the foundation tenant-scoped slug/username.)
--
-- Hand-authored (NOT generated by `prisma migrate dev`) to avoid Prisma's auto-diff
-- proposing to drop the raw-SQL-managed full-text search columns on `products`
-- (search_vector / search_category_name), which are intentionally not in schema.prisma.

-- Category: (name, parentId) was globally unique -> scope by tenant.
DROP INDEX IF EXISTS "categories_name_parentId_key";
CREATE UNIQUE INDEX "categories_tenantId_name_parentId_key" ON "categories"("tenantId", "name", "parentId");

-- ProductVariant: sku was globally unique -> scope by tenant.
DROP INDEX IF EXISTS "product_variants_sku_key";
CREATE UNIQUE INDEX "product_variants_tenantId_sku_key" ON "product_variants"("tenantId", "sku");

-- UiSetting: key was globally unique (blocked per-tenant settings) -> scope by tenant.
DROP INDEX IF EXISTS "ui_settings_key_key";
CREATE UNIQUE INDEX "ui_settings_tenantId_key_key" ON "ui_settings"("tenantId", "key");
